name: CI/CD Pipeline

permissions:
  contents: read
  security-events: write
  actions: read

on:
  push:
    branches: 
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run tests
      run: npm test
      
    - name: Build package
      run: npm run build
      
    - name: Test CLI installation
      run: |
        npm pack
        npm install -g ./auth-pkce-*.tgz
        auth-pkce --version
        auth-pkce --help

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: typescript
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v4
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:typescript"

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [test, security]
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'
        registry-url: 'https://registry.npmjs.org/'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update package version from tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        npm version $TAG_VERSION --no-git-tag-version
        echo "Updated package.json to version $TAG_VERSION"
        
    - name: Build package
      run: npm run build
      
    - name: Verify package contents
      run: |
        npm pack --dry-run
        ls -la dist/
        cat package.json | grep version
        
    - name: Publish to npm
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        if [[ $TAG_VERSION =~ -[a-zA-Z] ]]; then
          # Prerelease version - extract prerelease identifier
          PRERELEASE_TAG=$(echo $TAG_VERSION | sed -n 's/.*-\([a-zA-Z][a-zA-Z0-9]*\).*/\1/p')
          echo "Publishing prerelease version $TAG_VERSION with tag: $PRERELEASE_TAG"
          npm publish --provenance --access public --tag $PRERELEASE_TAG
        else
          # Stable release
          echo "Publishing stable version $TAG_VERSION"
          npm publish --provenance --access public
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}